### ISSUE TITLE
Giving up on TDD from Jquery on

### ISSUE THREAD

**Issue by martinbetz** [mjhea0/flaskr-tdd#12]
Hey there,

I like the tutorial and can follow along very well. Up until you get to "Jquery". From there on, you give up the concept of write test first, let it fail, fix it. Instead you start with (unexplained) code first and write the tests later. Actually, I could not learn very much from that point on. You might think about changing the order down there, or leave it out completely if it does not add value to your otherwise excellent TDD tutorial.

**Comment by mjhea0** [comment]
jQuery hits the front-end, so in order to test that, you would have to do either functional or integration tests.
