### ISSUE TITLE
h2 tag id must be specified in the new Bootstrap 3 templates

### ISSUE THREAD

**Issue by feelosophy13** [mjhea0/flaskr-tdd#13]
Under "More Color", for index.html.

The code should be: 
```
<li class="entry"><h2 id={{ entry.id }}>{{ entry.title }}</h2>{{ entry.text|safe }}
```

Instead of: 
```
<li class="entry"><h2>{{ entry.title }}</h2>{{ entry.text|safe }}
```

Otherwise, jQuery cannot select the post item and delete when clicked.

**Comment by mjhea0** [comment]
Want to submit a pull request?

**Comment by mjhea0** [comment]
Wait .. Doesn't that get updated here -> https://github.com/mjhea0/flaskr-tdd#indexhtml
