### ISSUE TITLE
add new feature to the tutorial

### ISSUE THREAD

**Issue by mjhea0** [mjhea0/flaskr-tdd#16]
Please include the code and the updated markdown file.

**Comment by aman-roy** [comment]
Can I do this? I am adding a search page for the blog.

**Comment by mjhea0** [comment]
Yes. Thank you!

**Comment by jQwotos** [comment]
I'm also interested in working on this. How about a user registration and login (using the database instead of fixed variables)?

**Comment by mjhea0** [comment]
@jQwotos sounds great!

**Comment by j-kon** [comment]
Wow this is cool

**Comment by mjhea0** [comment]
@j-kon want to help?
