### ISSUE TITLE
Question regarding changes in text_index()

### ISSUE THREAD

**Issue by addianto** [mjhea0/flaskr-tdd#19]
Hello!

I just starting following your TDD tutorial and have reached the [Second Test section](https://github.com/mjhea0/flaskr-tdd#second-test). I was wondering why you changed the `test_index()` from asserting a Hello World page to giving a 404 error. What was the reasons for the changes?

In the [First Test section](https://github.com/mjhea0/flaskr-tdd#first-test), I kind of understand the motivation why testing the index page. It is for asserting that a Hello World page is returned whenever there is a request going to `/` path. But in the [Second Test section](https://github.com/mjhea0/flaskr-tdd#second-test), the test was changed to assert a 404 error and making the app to not returning a Hello World page.

**Comment by mjhea0** [comment]
No, real reason. Just wanted to use that same route rather than keeping the hello world. Feel free to keep it in your code.
