### ISSUE TITLE
Consider using `python3 -m venv `

### ISSUE THREAD

**Issue by 9034725985** [mjhea0/flaskr-tdd#21]
The page at https://docs.python.org/3/library/venv.html says 

> Note The pyvenv script has been deprecated as of Python 3.6 in favor of using python3 -m venv to help prevent any potential confusion as to which Python interpreter a virtual environment will be based on. 

Should the readme reflect this change?

**Comment by mjhea0** [comment]
Updated https://github.com/mjhea0/flaskr-tdd/pull/24!
