### ISSUE TITLE
little typo

### ISSUE THREAD

**Issue by dongido001** [mjhea0/flaskr-tdd#25]
I believe there is a little typo on the readme,

On this line `
    NOTE: You know that you are in a virtual env, as the actual "env" is now show before the $ in your terminal - (env). ` . 

I think the `show` should be `showing`

**Comment by mjhea0** [comment]
Nice catch! Want to issue a PR?

**Comment by dongido001** [comment]
yeah @mjhea0

**Comment by dongido001** [comment]
@mjhea0 done.

**Comment by mjhea0** [comment]
Just merged. Thanks!
