### ISSUE TITLE
Create a Gitbook instead of using the README 

### ISSUE THREAD

**Issue by Jpfonseca** [mjhea0/flaskr-tdd#27]
Hi I just found your repo while scrolling the Hacktoberfest issues. I think that your idea is great, but I just couldn't read it all .
My suggestion use a Gitbook(gitbook.com) instead of the README for the tutorials . It will improve readability  and it will make more people use your tutorials

**Comment by mjhea0** [comment]
Sounds great! Want to add the PR?

**Comment by Jpfonseca** [comment]
I will do my best

**Comment by mjhea0** [comment]
Done. @Jpfonseca 

https://github.com/mjhea0/flaskr-tdd/tree/gitbook/book
