### ISSUE TITLE
Add a section: How to scale your app

### ISSUE THREAD

**Issue by rdpoor** [mjhea0/flaskr-tdd#44]
I think it's _incredibly_ cool that you've actively curated this project for over five years.  It's fun to read the commit history and see how it has evolved.

For users who are starting out, it might be useful to give some guidance on how to refactor a Flask / Jinja / SQLAlchemy / unittest based project as it grows.  I'm _far_ from being an expert, but some ideas that come to mind:

* Refactor app-test.py into tests/test-*.py
* Refactor models.py in to models/*.py
* Use templates to avoid repetition in the .html files
* Use [splinter](https://github.com/cobrateam/splinter) or equivalent for testing browser interactions
* Refactor configuration variables into their own file

**Comment by SaurabhBansalInferstat** [comment]
We could also Jump into using event driven programming and use rabbit mq as a queue and postgres or mongo as an event store
