### ISSUE TITLE
Posts can be deleted even though user isn't logged in

### ISSUE THREAD

**Issue by jeremiasbaur** [mjhea0/flaskr-tdd#52]
Currently, posts can be deleted if you aren't logged in.

**Comment by mjhea0** [comment]
Yes, that's done on purpose. This is left up to the reader to check his/her understanding and implement this on their own. Do you want to take a stab at it and create a PR?

**Comment by jeremiasbaur** [comment]
Yes, sounds good! I will do it.

**Comment by jeremiasbaur** [comment]
I created a PR: https://github.com/mjhea0/flaskr-tdd/pull/53

**Comment by mjhea0** [comment]
Thanks! I'm planning on updating the tutorial to Python 3.8 here soon. I'll look at your PR at the same time.

**Comment by jeremiasbaur** [comment]
Alright, great! I didn't update the tutorial with the changes. So you still need to do this if you merge.

**Comment by mjhea0** [comment]
https://github.com/mjhea0/flaskr-tdd/pull/56
