### ISSUE TITLE
Consider renaming app.test.py to something else

### ISSUE THREAD

**Issue by markdall** [mjhea0/flaskr-tdd#58]
This is mostly an FYI as I don't really want or expect you to change the name everywhere. Maybe you could add a note about it to the tutorial: VSCode's python test extensions don't handle dots in the filename per [this](https://github.com/microsoft/vscode-python/issues/8490#issuecomment-553181223). Test discovery fails, etc. If you rename it to app_test.py suddenly everything works as desired. They say this is intentional.

**Comment by mjhea0** [comment]
Thanks for the note. I'll make the change the next time I update the tutorial.

**Comment by mjhea0** [comment]
addressed in https://github.com/mjhea0/flaskr-tdd/pull/63
