### ISSUE TITLE
delete_entry doesn't check if a post actually exists

### ISSUE THREAD

**Issue by ren1982** [mjhea0/flaskr-tdd#59]
Not sure if this is intended behavior, but: The `test_delete_message` test will always succeed (prior to implementing `login_required`) regardless of whether or not there are existing posts as long as that route is correctly defined because `delete_entry` doesn't send an error if the `post_id` doesn't actually exist in the database, meaning that regardless of how many posts you actually have, if you go to `/delete/1` or `/delete/9999999999999`, you'll always get the JSON saying Post Deleted. (The flash message doesn't do anything, either, as it doesn't send you to an HTML page.)

Found this out coz I was having problems implementing tests for search, until I remembered that `setUp` and `tearDown` are run before and after _every_ test and not at the start and at the end of the entire test suite.

**Comment by mjhea0** [comment]
addressed in https://github.com/mjhea0/flaskr-tdd/pull/63
