### ISSUE TITLE
First test database test

### ISSUE THREAD

**Issue by GiorgosTharropoulos** [mjhea0/flaskr-tdd#68]
Hello,

The first time we test for the existence of the test.db, we expect the test.db file to located at tddflaskr/test.db. But the file is created inside the project/ directory. You have specified that 3 tests should fail, the initial test should pass. Unfortunately, it does not because as I said, the test database is created inside the project directory and not at the root.

The test would pass if the tests are run within the project directory, am I missing something? 

Thank you for the excellent tutorial!

**Comment by mjhea0** [comment]
I'd have to look at the structure of your project. Is it on GitHub?

**Comment by GiorgosTharropoulos** [comment]
Hello,

You can find my project here: https://github.com/GiorgosTharropoulos/tddflaskr

Thank you!

**Comment by mjhea0** [comment]
I see the issue. The "tests" directory needs to be placed outside the "project" directory. See the final project structure here: https://github.com/mjhea0/flaskr-tdd.

**Comment by GiorgosTharropoulos** [comment]
Sorry about that ! Thank you
