### ISSUE TITLE
(env)$ python create_db.py

### ISSUE THREAD

**Issue by sid2021** [mjhea0/flaskr-tdd#69]
First of all I would like to thank you for a very nicely written tutorial. 

I found a small problem while trying to create a database. Using the command (env)$ python create_db.py generates the following error:

"ImportError: cannot import name 'db' from partially initialized module 'project.app' (most likely due to a circular import) (C:\***\flaskr-tdd\project\app.py)"

which is probably related to the fact that project.app imports from project.models and on the other hand project.models imports from project.app.

What is the correct way to solve this issue?

**Comment by sid2021** [comment]
What is interesting vscode automatically pushes this line of code ```from project import models``` on top of project.app.

**Comment by mjhea0** [comment]
I'd have to look at the structure of your project. Is it on GitHub?

**Comment by sid2021** [comment]
I discovered the root of the problem. As mentioned before the error occured then the line ```from project import models``` was placed at the beginning of app.py. Even though I was pasting this line of code after ```db = SQLAlchemy(app)``` (in order to avoid this error) python formatter (autopep8) was pushing it to the top of the file. When I changed formatter to black the problem did not exist.
