### ISSUE TITLE
Circular depedency when adding SQLAlchemy

### ISSUE THREAD

**Issue by nigelm** [mjhea0/flaskr-tdd#72]
I ended up with circular dependency errors when adding SQLalchemy in:-

```
ImportError: cannot import name 'db' from partially initialized module 'flaskr_tdd.app' (most likely due to a circular import) (/Users/nigel/Tasks/learning/flaskr-tdd/flaskr_tdd/app.py)
```

I ended up changing the top of `models.py` to
```python
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
```

and in `app.py` removing the SQLAlchemy import and changing 
```python
from flaskr_tdd.models import db
...
# create and initialize a new Flask app
app = Flask(__name__)
# load the config
app.config.from_object(__name__)
db.init_app(app)
db.app = app
```

which at least feels like an attempt to keep the db definition down in the models...

**Comment by travwritescode** [comment]
This solution worked for me and it appears there may be a version issue with SQLAlchemy when trying to create the DB. Created a new issue and linked it above!
